/*
 * contains the framework of the program
 */
package connect4summative2;

//imports
import PanelLinking.SendChangeSignal;
import PanelLinking.SendChangeString;
import GUI.ControlPanel;
import GUI.SplashScreenPanel;
import java.awt.CardLayout;

/**
 * Contains the JFrame used to display all the panels
 *
 * @author Richard Tu
 */
public class BaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form baseFrame
     */
    public BaseFrame() {
        initComponents();

        //sets up stackPanel and propertyChangeListener
        StackPanel.setLayout(new CardLayout());
        SendChangeSignal setUpGame = new SendChangeString();

        //adds the panels for the game to stackPanel
        StackPanel.add(new SplashScreenPanel(setUpGame), "start");
        StackPanel.add(new ControlPanel(setUpGame), "game");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StackPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        javax.swing.GroupLayout StackPanelLayout = new javax.swing.GroupLayout(StackPanel);
        StackPanel.setLayout(StackPanelLayout);
        StackPanelLayout.setHorizontalGroup(
            StackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        StackPanelLayout.setVerticalGroup(
            StackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(StackPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * makes the screen visible
     *
     */
    public static void makeVisible() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StackPanel;
    // End of variables declaration//GEN-END:variables
}
