/*
 * Contains all classes pertaining to the GUI
 */
package GUI;

/**
 * contains the panel which shows instructions on how to use the interface
 *
 * @author User
 */
public class HelpPanel extends javax.swing.JPanel {

    int index;
    String[] instructions;

    /**
     * Creates new form HelpPanel
     */
    public HelpPanel() {
        initComponents();
        //stores where the index is at
        index = 0;
        //creates a new array to store all the instructions
        instructions = new String[7];

        //sets up the instructions
        instructions[0] = "1. To select accounts click on the drop\n"
                + "down menus underneath the title. To\n"
                + "filter options type ";
        instructions[1] = "2. To reset the board and accounts click\n"
                + "the reset button";
        instructions[2] = "3. To create an account type a name into\n"
                + "the area beside Name/Filter and click\n"
                + "create. No special characters (<, &)";
        instructions[3] = "4. To turn on the computer player go to\n"
                + "the account selection and select either \n"
                + "Computer1 or Computer2. Difficulty \n"
                + "selection will be underneath";
        instructions[4] = "5. To delete an account select an account\n"
                + "from the drop down list beside the box\n"
                + "beside Name/Filter and click delete";
        instructions[5] = "6. To find a name in the leaderboards \n"
                + "type the desired name in the filter above\n"
                + "the leaderboards";
        instructions[6] = "7. The colour of the buttons shows\n"
                + "which player goes next (note that coloured\n"
                + "arrows point to which account is which \n"
                + "colour) and who won";
        //disables backwards button
        BackwardButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        BackwardButton = new javax.swing.JButton();
        ForwardButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(200, 200, 200));
        setPreferredSize(new java.awt.Dimension(450, 210));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. To select accounts click on the drop\ndown menus underneath the title. To\nfilter options type ");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Instructions");

        BackwardButton.setText("Backward");
        BackwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackwardButtonActionPerformed(evt);
            }
        });

        ForwardButton.setText("Forward");
        ForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackwardButton)
                    .addComponent(ForwardButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * defines what the forward and back buttons do
     *
     * @param indexChange - stores the change in index
     */
    private void buttonAction(int indexChange) {
        //adds indexChange to index
        index = index + indexChange;
        //sets the Instruction Panel to a certain instruction at element index
        jTextArea1.setText(instructions[index]);

        //determines if the forward or backward button needs to be disabled depending
        //on whether or not the element currently selected is the end of the array
        //or 0 (start of the array). Otherwise enable both
        if (index == instructions.length - 1) {
            ForwardButton.setEnabled(false);

        } else if (index == 0) {
            BackwardButton.setEnabled(false);

        } else {
            ForwardButton.setEnabled(true);
            BackwardButton.setEnabled(true);
        }
    }
    private void BackwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackwardButtonActionPerformed
        buttonAction(-1);
    }//GEN-LAST:event_BackwardButtonActionPerformed

    private void ForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardButtonActionPerformed
        buttonAction(1);
    }//GEN-LAST:event_ForwardButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackwardButton;
    private javax.swing.JButton ForwardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
