/*
 * Contains all classes pertaining to the GUI
 */
package GUI;

//imports
import PanelLinking.SendChangeSignal;
import java.awt.CardLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 * Contains the display for the splash screen
 *
 * @author Richard Tu
 */
public class SplashScreenPanel extends javax.swing.JPanel {

    SendChangeSignal quickSetup;

    /**
     * Creates new form SplashScreenPanel
     *
     * @param quickSetup1
     */
    public SplashScreenPanel(SendChangeSignal quickSetup1) {
        initComponents();

        //stores the PropertyChangeListener connected to the control panel
        //and adds a property change listener to facilitate communication
        quickSetup = quickSetup1;
        quickSetup.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent pce) {
                ;
            }
        });
        //displays an image
        javax.swing.ImageIcon splash = new javax.swing.ImageIcon("op2.png");
        splashPhoto.setIcon(splash);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        QuickStartButtonPvP = new javax.swing.JButton();
        QuickStartButtonPvC = new javax.swing.JButton();
        DeleteFileButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        splashPhoto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        Title.setFont(new java.awt.Font("Segoe UI Black", 2, 64)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 255));
        Title.setText("Connect 4");

        StartButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        StartButton.setText("Start");
        StartButton.setActionCommand("S");
        StartButton.setPreferredSize(new java.awt.Dimension(150, 50));
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        QuickStartButtonPvP.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        QuickStartButtonPvP.setText("QuickStart (PvP)");
        QuickStartButtonPvP.setPreferredSize(new java.awt.Dimension(150, 50));
        QuickStartButtonPvP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickStartButtonPvPActionPerformed(evt);
            }
        });

        QuickStartButtonPvC.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        QuickStartButtonPvC.setText("QuickStart (PvC)");
        QuickStartButtonPvC.setPreferredSize(new java.awt.Dimension(150, 50));
        QuickStartButtonPvC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickStartButtonPvCActionPerformed(evt);
            }
        });

        DeleteFileButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        DeleteFileButton.setText("Delete File");
        DeleteFileButton.setActionCommand("S");
        DeleteFileButton.setPreferredSize(new java.awt.Dimension(150, 50));
        DeleteFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        splashPhoto.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(QuickStartButtonPvC, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(QuickStartButtonPvP, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DeleteFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(splashPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(splashPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuickStartButtonPvP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuickStartButtonPvC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * shared code used to switch screens
     */
    void switchScreen() {
        //gets the sources cardlayout and switches to the game screen
        javax.swing.JPanel a = (javax.swing.JPanel) this.getParent();
        CardLayout b = (CardLayout) a.getLayout();
        b.show(a, "game");
    }

    /**
     * defines what the start button does
     *
     * @param evt - not used
     */
    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        switchScreen();
    }//GEN-LAST:event_StartButtonActionPerformed
    /**
     * defines what the PvP start button does
     *
     * @param evt - not used
     */
    private void QuickStartButtonPvPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickStartButtonPvPActionPerformed
        switchScreen();
        //sets up the game using quickSetup 
        quickSetup.setName("b");
    }//GEN-LAST:event_QuickStartButtonPvPActionPerformed
    /**
     * defines what the PvC start button does
     *
     * @param evt - not used
     */
    private void QuickStartButtonPvCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickStartButtonPvCActionPerformed
        switchScreen();
        //sets up the game using quickSetup
        quickSetup.setName("c");
    }//GEN-LAST:event_QuickStartButtonPvCActionPerformed
    /**
     * deletes the current stored file and creates a new blank one
     *
     * @param evt - not used
     */
    private void DeleteFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFileButtonActionPerformed
        Files.FileManipFunctions.createFile();
        //tells the game to update the lists
        quickSetup.setName("delete");
    }//GEN-LAST:event_DeleteFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteFileButton;
    private javax.swing.JButton QuickStartButtonPvC;
    private javax.swing.JButton QuickStartButtonPvP;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel splashPhoto;
    // End of variables declaration//GEN-END:variables
}
